[workspace]
members = [
    "node/kusama",
#    "node/polkadot",
    "pallets/*",
    "runtime/kusama",
#    "runtime/polkadot",
    "primitives",
]

exclude = [
    "runtime/kusama",
#    "runtime/polkadot",
]

[profile.release]
panic = "unwind"
