name: Docker Image

on:
  push:
    branches: [main]
    tags:
      - "v*"
      - "staging*"
      - "qa*"

jobs:
  dockerimage:
    if: github.repository == 'dorafactory/dorafactory-node'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        bin: ["dorafactory-node"]

    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
          fetch-depth: 2
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            BIN=${{ matrix.bin }}
            PROFILE=release
          tags: df/${{ matrix.bin }}:${{ steps.docker_tag.outputs.value }}
      - name: Image digest
        if: steps.has_changed_path.outputs.changed == 'true'
        run: echo ${{ steps.docker_build.outputs.digest }}
