name: Docker Image

on:
  push:
    branches: [main]
    tags:
      - "v*"
      - "staging*"
      - "qa*"

jobs:
  build-image:
    if: github.repository == 'dorafactory/dorafactory-node'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        bin: ["dorafactory-node"]
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
          fetch-depth: 2
      - name: Checkout LFS objects
        run: git lfs checkout
       - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ap-southeast-1
      - name: Build image
        env:
          PROFILE: "release"
        run: |
          docker build --build-arg BIN=${{ matrix.bin }} PROFILE=$PROFILE -t dorafactory-node:local -f ./Dockerfile .
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Tag, push  image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dorafactory-node
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker tag dorafactory-node:local $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          build-args: |
            BIN=${{ matrix.bin }}
            PROFILE=release
          tags: df/${{ matrix.bin }}:alpha
      - name: Image digest
        if: steps.has_changed_path.outputs.changed == 'true'
        run: echo ${{ steps.docker_build.outputs.digest }}
